[KFT-34] Create Login/Register Pages
kraftie-co/core-client-ui pull request #2
Opened 2022-12-03 14:20 UTC by albu-alex

Have fun!

2022-12-03 14:58 UTC, TheXGeneral requested changes

2022-12-03 14:58 UTC, TheXGeneral commented on .idea/codeStyles/Project.xml
> +    <HTMLCodeStyleSettings>
These should be added to gitignore.

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.module.css
> +.header {
Let's convert these to styled components

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +      alert(t('Passwords do not match. Please try again'));
Let's move this functionality in redux and api call into a dedicated file under services/api. 
in redux, please create a slice, create an asyncThunc and pass data to the login container

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +      <div className={styles.header}>
please convert divs to Flex/ Box from rebass

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +      alert(t('Passwords do not match. Please try again'));
Please to do not use alerts. I suggest to use [toasters ](https://www.npmjs.com/package/react-toastify)

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +        <h1>{t('Join us, Krafter!')}</h1>
Please use the Typography component with the title configuration from theme

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +            style={arePasswordsMatched ? { borderColor: 'red' } : { borderColor: '#034C65' }}
Plase do not use hardcoded values. You have access to theme in each component with the help of useTheme hook from styled components

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.styled.js
> +  paddingBottom: '5vh',
Please use spacing from theme

2022-12-03 14:58 UTC, TheXGeneral commented on .idea/codeStyles/Project.xml
> +    <HTMLCodeStyleSettings>
`.idea` added in gitignore should do the trick

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.js
> +        <h1>{t('Hello, Krafter!')}</h1>
I preffer to use i18next with token aka t('HELLO_KRAFTER') and in services/locales you add in that JSON the key and the translated value. 
PS. Please keep that JSON sorted

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.js
> +          <input
Input will be used an reused. Please export it into a separate component, style it there and import it already styled. 
I basically want a wrapper component around input, to style it and even add some custom functionality (error show)

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/index.js
> +
Let's split these in 2 separate folders

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Home/Home.js
> +      navigate('/login');
Not a valid use-case for client app

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Home/Home.js
> +  const isLoggedIn = localStorage.getItem('user-token');
let's have localStorage as an util. We will have 3 functions> load, save and remove. Stringify and respectively parse the data from localStorage - try catch these operations - they might fail

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.js
> +          {t('Do not have an account?')} <a href={'/register'}>{t('Register.')}</a>
Please do not use anchor tags with href. They are problematic in a context of a React App. Will explain in detail. Use Link from react-router-dom, or better, the navigate function from useNavigate Hook

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +      alert(t('Passwords do not match. Please try again'));
there is an example in Counter container of how to link redux to component.

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +        <button className={styles.button} onClick={registerRequest}>
Let's use button from rebass + let's have a separate button component, styled and everything

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.js
> +import styles from 'Login.module.css';
Please keep local references consistent. Use ./ for local dependencies.

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Register.js
> +        <input
Let's switch to an email based auth system

2022-12-03 14:58 UTC, TheXGeneral commented on src/containers/Login/Login.module.css
> +}
Even though I highly appreciate your creativity, I will soon add design mocks to figma :)

2022-12-04 16:03 UTC, albu-alex commented on src/containers/Login/Login.js
> +          <input
Tried to do that, but had some issues. Will try again

2022-12-04 16:12 UTC, albu-alex commented on src/containers/Login/index.js
> +
Is this really needed?

2022-12-04 16:17 UTC, albu-alex commented on src/containers/Login/Login.js
> +          {t('Do not have an account?')} <a href={'/register'}>{t('Register.')}</a>
Thank you for explanation!

2022-12-04 17:42 UTC, TheXGeneral commented on src/containers/Login/index.js
> +
I think it will enhance readability (it will be easier to navigate trough folders and find what you want to edit). If you don't wanna do this, I agree with that opinion, but at least let's rename the folder to `Sign` or anything that inform us that we have both Login and Register there

2022-12-04 18:41 UTC, albu-alex commented on src/containers/Home/Home.js
> +      navigate('/login');
Left a // TODO here. Maybe we should implement this after we link the BE and FE together

2022-12-06 20:39 UTC, albu-alex commented on src/containers/Login/Register.js
> +        <button className={styles.button} onClick={registerRequest}>
Button used, will have to move to separate component

2022-12-11 09:53 UTC, albu-alex commented on src/containers/Login/Register.js
> +        <input
Maybe we should review this afterwards.

2022-12-11 20:14 UTC, albu-alex commented on src/containers/Login/Register.js
> +      alert(t('Passwords do not match. Please try again'));
Managed to create the infrastructure, but did not manage to adapt it to examples.

2022-12-18 09:37 UTC, TheXGeneral approved these changes

2022-12-18 12:33 UTC, merged