navbar with no functionality for menus
kraftie-co/core-client-ui pull request #3
Opened 2022-12-04 13:53 UTC by 912-BUZAN-DAN-ALEXANDRU

2022-12-04 14:34 UTC, TheXGeneral requested changes

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +import cart_icon from './res/cart_icon.png';
Please move icons into the public folder

2022-12-04 14:34 UTC, TheXGeneral commented on package.json
>    "dependencies": {
At some point you run npm install instead of yarn install. Please remove the package-lock.json file

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +          Jewelry & Accessories
Please move this labels into a constants.js file set at the root of the project. Have an array of objects, each object being> 
key: 'NAVBAR_CATEGORY_JEWELRY_AND_ACCESSORIES'
name> 'JEWELRY_AND_ACCESSORIES'
label: 'JEWELRY_AND_ACCESSORIES'

After this, add in services/locales translation values 
"JEWELRY_AND_ACCESSORIES": "Jewelry & Accessories"

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +          Kraftie
Please do not use Text component from rebass. We have a typography component. Use font presets from theme

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +        </Text>
After that, map over that array and display the elements. My suggestion is to use Flex, with a fixed size, 70-80% and put elements with space-between as justify-content property.

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +      <Box minHeight={50} width={1 / 10} backgroundColor={'#034C65'} alignItems="center">
Please do not set fixed height. Height will be computed as lineHeight + paddingBottom + paddingTop. Do not set a fix value for it, just make the bar a Flex and it will arrange itself

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +    <Flex width={1} height={100} flexWrap="wrap" flexDirection={'row'} alignItems="center" backgroundColor={'#0B6884'}>
Code becomes hard to read if you keep the styling in jsx. Please create styledComponents and move the styling there

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +    <Flex width={1} height={100} flexWrap="wrap" flexDirection={'row'} alignItems="center" backgroundColor={'#0B6884'}>
Please do not use hardcoded values for colors. You will find them in theme

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +      <Box minHeight={100} width={1 / 20} backgroundColor={'#0B6884'}></Box>
Please do not use empty boxes when you actually want a margin :)

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +      <Box width={1 / 20} minHeight={100} alignItems="center" backgroundColor={'#0B6884'}>
Instead of using so many margins, use a FlexBox for this line and set align-items center to all the div. the searchBar will controll the height of the Flex, from that on, all elements will arrange themselves

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +function Navbar() {
Please adapt you code the fit the new design

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/SearchBar/SearchBar.js
> +  changeValue: bindActionCreators((newValue) => searchBarActions.changeValue(newValue), dispatch),
This can be simplified `changeValue: bindActionCreators(searchBarActions.changeValue, dispatch)`

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/SearchBar/SearchBar.js
> +          height={50}
Please move these styleings into a styled Component

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/NavBar/NavBar.js
> +function Navbar() {
Let's split this into TopBar and SubBar and then a NavBar that contains both. 
I basically want 2 files, one for TopBar (that with search, buttons and others)  and one for SubBar aka the productType. 
NavBar will be 

```
<> 
<TopBar /> 
<SubBar />
</>
```

2022-12-04 14:34 UTC, TheXGeneral commented on src/components/SearchBar/SearchBar.js
> +//import SearchIcon from '@mui/icons-material/Search';
Pelase remove if not used

2022-12-18 09:34 UTC, CiraStefan approved these changes

2022-12-18 09:36 UTC, closed without merging